{
  {
    "id": 001,
    "name": "VOX Table",
    "address": "110 South Lamar Suite 2140",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78704",
    "phone number": "(512) 375-4869",
    "brunch": "Weekend, 11am-2pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.voxtableaustin.com",
    "review": "Some people prefer their brunch to be basic, but they are probably the same folks who made Meghan Trainor a thing. Those of us with more taste or who prefer something a bit more creative appreciate that chef Joe Anguiano has his own take on brunch classics like a potato churro blini topped with smoked Tasmanian trout or a Duroc pork hash swimming in salsa verde. Beverage director JR Mocanu's drinks are equally innovative. Order the Sif's Song, tomato- and caper berry-infused aquavit served with a simple syrup of thyme, sea salt, orange peel, and black pepper."
  },
  {
    "id": 002,
    "name": "Sway",
    "address": "1417 South 1st Street",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78704",
    "phone number": "(512) 326-1999",
    "brunch": "Weekend, 11am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.swayaustin.com",
    "review": "Barely a month old, Sway's Thai-inflected brunch is already drawing crowds. Familiar favorites are completely transformed by chef Martin Wilda's adventurous palate. Chicken and waffles are served with a green nahm jihm and maple-lemon butter, biscuits and gravy uses bacon powder and crispy basil leaf, and a simple mussel omelette gets some spark from sambal. The cocktail menu has a few tricks too, reinventing the mimosa with hibiscus and grapefruit, and turning the michelada into a cucumber tomatillo masterpiece."
  },
  {
    "id": 003,
    "name": "Jacoby's Restaurant & Mercantile",
    "address": "3235 East Cesar Chavez Street",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78702",
    "phone number": "(512) 366-5808",
    "brunch": "Weekend, 10am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.jacobysaustin.com",
    "review": "The Hill Country is a beautiful place to brunch, but the Lyft ride would cost a mortgage payment. Luckily, Jacoby's is just as scenic. The brunch pulls from Texas' culinary heritage – duck confit migas with queso and ranchera salsa; schnitzel with country ham, poached eggs, smoked Gouda gravy, and arugula; and chicken-fried steak and waffles. Don't miss the pastries, like a cranberry-and-pecan scone and the best blueberry bread this side of your grandma's house."
  },
  {
    "id": 004,
    "name": "Monger's Market + Kitchen",
    "address": "2401 E. Cesar Chavez",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78702",
    "phone number": "(512) 215-8972",
    "brunch": "Weekend, 11:30am-3:30pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.mongersaustin.com",
    "review": "Although chef Shane Stark's menu has plenty of hearty foods to coat a hung over belly (we especially dig the Low Country Benedict, a perfect biscuit topped with a crab cake and Old Bay hollandaise), his lighter dishes allow us to pretend we are making healthy choices while downing our third michelada. The raw bar is a must, of course, serving a bright hamachi crudo, blue crab, oysters, and more. But there's plenty of surprises, like a sunny grilled Little Gem lettuce salad with white anchovies, or a playful version of angels on horseback with pork rillette, raisin, and pecan crème fraîche."
  },
  {
    "id": 005,
    "name": "Geraldine's",
    "address": "605 Davis Street",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78701",
    "phone number": "(512) 476-4755",
    "brunch": "Sunday, 9am-1:30pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.geraldinesaustin.com",
    "review": "Music is part and parcel of this Rainey newcomer, so it's no wonder that their brunch features live local jazz. Chef Frank Mnuk hits all the right notes with a down-home fried potato tot hash with braised pork ribs; a red quinoa breakfast salad with kale, blueberry, and radish; and a corn skillet with Benton's ham and mustard greens. Bar operations chief Jennifer Keyser keeps things humming with drinks like the Mellow Yellow (yellow Chartreuse, Dolin blanc, lemon juice, soda, and agave) and the Sunday Bloody Sunday (Vida mezcal, seasonal sangrita with a chile-lime salt rim)."
  },
  {
    "id": 006,
    "name": "Café no Sé",
    "address": "1603 South Congress Avenue",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78704",
    "phone number": "(512) 942-2061",
    "brunch": "Weekend, 10am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.cafenoseaustin.com",
    "review": "Few menus in town celebrate the vegetable as much as Michael Paley's California-inspired offerings at No Sé. Dishes like avocado toast with a soft boiled egg, upland cress, and aleppo-pickled carrots, or poached eggs, green garbanzo curry, quinoa, and bok choy aren't so heavy that you will have to skip barre class. But we recommend you indulge a little. Pastry chef Amanda Rockman will make you swoon with apple frangipane croissants and crust kouign amanns. You can always tell your gym partner that you got a flat tire – just make sure you don't post to Instagram."
  },
  {
    "id": 007,
    "name": "Central Standard",
    "address": "1603 South Congress Avenue",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78704",
    "phone number": "(512) 942-0823",
    "brunch": "Weekend, 11am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.centralstandardaustin.com",
    "review": "If you are looking for more of Rockman's decadent baked goods, go next door to Central Standard. Her cinnamon roll is what you always wished Cinnabon tasted like and her cake donuts are worth risking a sugar crash. Paley's fare here is a little heartier than at his South Congress Hotel sister restaurant. The shrimp and grits are studded with pancetta and butter; an omelette includes fried oysters, bacon, and Parmesan; and the Benedict is served on a potato latke. Don't leave without ordering something from the vast raw bar, featuring everything from Maine lobster to Middleneck clams."
  },
  {
    "id": 008,
    "name": "Juan In a Million",
    "address": "2300 E. Cesar Chavez St.",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78701",
    "phone number": "(512) 472-3872",
    "brunch": "Daily, 7am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.juaninamillion.com",
    "review": ""
  },
  {
    "id": 009,
    "name": "Juliet Ristorante",
    "address": "1500 Barton Springs Rd.",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78704",
    "phone number": "(512) 479-1800",
    "brunch": "Weekend, 10am-2pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.juliet-austin.com",
    "review": "Juliet's lush patio is one of the best ways to while away an Austin weekend. Start the day with a brisk swim in Barton Springs Pool, then warm up with one of chef Jacob Weaver's Italian starters like Egg in a Hole with 'nduja gravy or a salmon crudo with fried capers. For the main event, we can never decide between the gulf shrimp and polenta made with a rich shallot burro bianco or the brunch risotto with peas, pancetta, parmigiana, and poached eggs (we like the alliteration too)."
  },
  {
    "id": 010,
    "name": "The Peached Tortilla",
    "address": "5520 Burnet Rd. #100",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78701",
    "phone number": "(512) 330-4439",
    "brunch": "Sunday, 10:30am-2:30pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.thepeachedtortilla.com",
    "review": "There is nothing expected about chef Eric Silverstein's brunch. A simple Benedict is amped up with brisket; steak and eggs pairs perfectly with kimchi; and sweet potato hash is spiced with Fresno chiles. The Loco My Moco is pure comfort – a beef patty topped with caramelized onions, fried egg, rice, and an addictive beef-dashi gravy. Those with a sweet tooth will love the subtly-flavored French toast topped with miso caramel, coconut whipped cream, and seasonal fruit."
  },
  {
    "id": 011,
    "name": "Wu Chow",
    "address": "500 W. Fifth",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78701",
    "phone number": "(512) 476-2469",
    "brunch": "Dim sum, 11am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.wuchowaustin.com",
    "review": "Fine, dim sum isn't exactly the same thing as brunch, but even the most Austin-y Austinite can sometimes get sick of migas. The star of the show here is chef Ling Qi Wu's cult Shanghai soup dumplings, but there's plenty of supporting players: delicate shumai filled with Tenderbelly pork and shrimp, crispy chicken and taro egg rolls, and Chinese broccoli with oyster sauce. Cozy up with a selection of hot teas, including so-hot-right-now pu-erh, or down one of Wu Chow's takes on the mimosa, with chrysanthemum tea instead of orange juice."
  },
  {
    "id": 012,
    "name": "Juniper",
    "address": "2400 E. Cesar Chavez #304",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78702",
    "phone number": "(512) 220-9421",
    "brunch": "Weekend, 10:30am-2:30pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.juniperaustin.com",
    "review": "Chef Nicholas Yanes' contemporary Italian brunch is pure dolce vita. The frittata gets zip from a tomato emulsion, and Meyer lemon and goat feta make roasted trumpet mushrooms uncommonly bright. And for our money, the whipped Dijon used with grilled fingerling potatoes has more sex appeal than Marcello Mastroianni. Don't skip out on pastry chef Kirsten Bellah's pastries (the honey-dipped doughnut holes are bellissima) or the Giancarlo, No!, a refreshing reviver of gin, Aperol, grapefruit, and soda."
  },
  {
    "id": 013,
    "name": "Banger's Sausage House & Beer Garden",
    "address": "79 Rainey",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78701",
    "phone number": "(512) 386-1656",
    "brunch": "Weekend, 11am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.bangersaustin.com",
    "review": "Whether hungover or straight-up ravenous, Banger's brunch offers guests an exemplary selection of hearty menu items sure to cure the most fastidious of ills. The Manmosa – an entire liter of Champagne with a splash of orange or cranberry juice – and the build-your-own Michelada bar provide a perfect start to a stick-to-your-ribs meal. Enjoy the Irishman's Hangover Cure ($12) – white & black pudding, banger, potato hash, baked beans, two fried eggs, and a grilled tomato – or perhaps the Kitchen Sink ($17), with a mound of beef tongue hash, two fried eggs, two pieces of bacon 'steak', sausage, a side of creamy grits, country ham, red-eye gravy, and toast. - ANNA TOON"
  },
  {
    "id": 014,
    "name": "The Bonneville",
    "address": "202 W. Cesar Chavez",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78701",
    "phone number": "(512) 428-4643",
    "brunch": "Sunday, 10:30am-2:30pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.thebonnevilleaustin.com",
    "review": "Brunch is the meal where the Bonneville truly shows its sterling quality. The menu features a range of innovative dishes created by chefs Jennifer Costello and Chris Hurley. Unforgettable entrées include bananas Foster French toast, chipotle-lime chicken hash, a smoked salmon plate with cream cheese and pumpernickel, and house-made popovers topped with spinach, ham, and poached egg, topped with Hollandaise. Side dishes include bacon tater tots, pecan sticky buns, and fresh coffee cake. Entrée prices range from $8-14, making brunch in this chic lakeside setting an incredible value. - KATE THORNBERRY"
  },
  {
    "id": 015,
    "name": "Searsucker",
    "address": "415 Colorado Street",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78701",
    "phone number": "(512) 394-8000",
    "brunch": "Saturday, 10am-3pm, Sunday, 10am-4pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.searsucker.com",
    "review": "Top Chef alum Brian Malarkey's high concept American bistro does it up right at brunch, which features a tantalizing selection of foodstuffs calculated to cure even the most persistent hangover. Excess is the word here where morning classics like eggs Benedict and potato hash are enhanced with praiseworthy piggy accoutrements. Searsucker's crisp, peppery bacon is practically a Sunday sacrament, while the shrimp with bacon grits ($14) have all the Southern charm of an authentic velvet Elvis. The cheddar biscuits with duck fat and sausage gravy won't let you down when you need to refuel. - RACHEL FEIT"
  },
  {
    "id": 016,
    "name": "Jo's Coffee Downtown",
    "address": "242 West Second Street",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78701",
    "phone number": "(512) 469-9003",
    "brunch": "Weekend, 8am-12pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.joscoffee.com",
    "review": "From healthy to heavy duty, every diner can find a favorite at the younger sister of the famed SoCo original. Counter service and pushed-back weekend hours are friendly to both early birds and hungover souls, though seating inside or on the patio can be limited during peak hours. Highlights are the expert hot/cold coffee bar, huge made-to-order pancakes ($2.50-7.50), an egg white omelette ($8.75), and breakfast tacos like the black bean, potato, and cheese ($3.50). - JESSI CAPE"
  },
  {
    "id": 017,
    "name": "Russian House",
    "address": "307 E. Fifth",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78701",
    "phone number": "(512) 428-5442",
    "brunch": "Saturday, 11am-4pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.russianhouseofaustin.com",
    "review": "For $25, you can immerse yourself in Russian cuisine – the only place in town you can find it – inside a space outfitted to evoke a Russian grandma's house. Every week, chef Vladimir Gribkov reaches beyond the borders of the restaurant's already-encyclopedic menu to represent areas of Russian cuisine that might be unfamiliar to diners. Patrons can kickstart their day with a shot of infused vodka (with a pickled veggie chaser), then dive into an all-you-can-eat smorgasbord of dumplings, soups, salads, and blinis. Don't miss the beet salad or pelmeni, if available. - MELANIE HAUPT"
  },
  {
    "id": 018,
    "name": "Threadgill's",
    "address": "301 W. Riverside",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78704",
    "phone number": "(512) 472-9304",
    "brunch": "Sunday Breakfast Buffet, 10am-1pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.threadgills.com",
    "review": " The buffet is loaded with Southern goodness, with items like migas, sweet-potato pancakes, and garlic cheese grits. There's also a custom omelet station for the egg freaks, bulging with options. The bands change weekly, and with Eddie Wilson's music connections, you know they'll be great. Come early, stake out a stage table, get a drink, and wait for the breakfast bounty. - MICK VANN"
  },
  {
    "id": 019,
    "name": "Swift's Attic",
    "address": "315 Congress Avenue Suite 200",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78701",
    "phone number": "(512) 482-8842",
    "brunch": "Sunday, 10:30am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.swiftsattic.com",
    "review": "If you're looking for outside-the-box brunch, here you can have chicken-fried Lockhart quail tenders with cheese biscuits and red eye gravy ($14), or black rice bibimbap topped with house-made kimchi ($11). We love the "Pragel & Trox" ($15) – freshly smoked trout, pickled onion, frisée, dill crème fraiche, and a poached egg inside a handmade pretzel bagel. For your sweet tooth, try the pecan cream cheese-stuffed French toast ($12) or decadent PB&J pancakes topped with blueberry compote and seared foie gras ($20). Wash it all down with $1 mimosas, or indulge in a complete Bloody Mary bar that includes crispy house-cured bacon and perfectly pickled veggies. - CLAUDIA ALARCÓN"
  },
  {
    "id": 020,
    "name": "El Naranjo",
    "address": "85 Rainey Street",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78701",
    "phone number": "(512) 474-2776",
    "brunch": "Sunday, 11am-2pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.elnaranjo-restaurant.com",
    "review": "El Naranjo is the quietly elegant brunch answer to Austin's ever-popular Mexican breakfast meme. Cocktails and brunch dishes are served at the bar, in the sleek and sun-dappled dining rooms, or on the enclosed patio. The menu offers a variety of classic egg preparations, braised beef and pork dishes, fish tacos, vegetable enchiladas, and excellent quesadillas of huitlacoche, roasted peppers, and mushrooms. Chef/owner Iliana de la Vega is justly feted for her exquisite salsas, and the fresh Mexican pastries by CIA-trained dessert chef Ana Torrealba are out of this world, especially when accompanied by chocolate or exceptionally delicious coffees. - MM PACK"
  },
  {
    "id": 021,
    "name": "Manuel's",
    "address": "301 Congress Avenue",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78701",
    "phone number": "(512) 472-7555",
    "brunch": "Sunday, 10am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.manuels.com",
    "review": "While it's billed as a 'jazz brunch,' the mood of Interior Mexico is perhaps more appropriately evoked with a traveling group of rootsy mariachis serenading your party as you enjoy tapas-style servings of filled potato tortas, quesadillas, and breakfast tacos. Hungry vegetarians will want to try the Flautas de Papa ($11), potato enchiladas that manage to be both light and filling; carnivores will love the Lomo de Res ($16), an upscale version of steak and eggs. Drink specials include $5 Mexican mimosas (orange juice, sparkling wine, and a splash of Bauchant orange liqueur) and serrano chile-spiked Bloody Marias. Those confined to the Downtown area will find another Manuel's within walking distance, on Congress Avenue. - M.H."
  },
  {
    "id": 022,
    "name": "Cherrywood Coffeehouse",
    "address": "1400 E. 38th½ St.",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78722",
    "phone number": "(512) 538-1991",
    "brunch": "Weekend, 10am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.cherrywoodcoffeehouse.com",
    "review": "This casual joint is a beloved weekend haunt in its neighborhood. Folks stake out tables in the comfortable interior or on the sunny, kid and dog-friendly patio, refreshing themselves with a full complement of coffee drinks and fresh juices, not to mention draft beers. Highly regarded for their burgers, the Cherrywood kitchen turns out excellent, affordable brunch fare with both Southern and Tex-Mex influences. We're partial to the spicy shrimp and grits ($9.49) and the NOLA-inspired crawfish Benedict ($10.99), but the over-stuffed Sol Taco ($4.99) will start any day off right. - V.B.W."
  },
  {
    "id": 023,
    "name": "Lucy's Fried Chicken",
    "address": "5408 Burnet Rd.",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78756",
    "phone number": "(512) 514-0664",
    "brunch": "Sunday, 10am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.lucysfriedchicken.com",
    "review": "During brunch, Lucy's offers hair-of-the-dog standards including $3 mimosas, salty dogs, and screwdrivers as well as $4.50 Bloody Marys. In addition to the Chicken N Waffles and the Lumberjack Hash, the brunch menu reimagines breakfast classics with dishes like the Burnet Benedict, which layers a jalapeño cornbread muffin with sausage, poached egg, and habanero Hollandaise, and the '42 Omelet, bursting with seasonal veggies, smoked Gouda, pumpernickel, and Sriracha yogurt. - A.T."
  },
  {
    "id": 024,
    "name": "Jack Allen's Kitchen",
    "address": "7720 Hwy. 71 W.",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78735",
    "phone number": "(512) 852-8558",
    "brunch": "Sunday, 10am-2pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.jackallenskitchen.com",
    "review": "Jack Allen’s has the well-deserved local reputation of producing handmade Southern and Southwestern food using fresh, local ingredients. The buffet ($16.99 per person) is a true groaning board, with four seasonal salads, chicken-fried meats with green chile gravy, 'Mama’s Sunday Chicken' (in mustard cream sauce with mushrooms), house-cured ham, green-chile-pork-and-egg casserole, layered enchiladas, pancakes, yard eggs to-order, local sausages, fruit, pastries, and much, much more. Drink specials include $3.50 hand-squeezed mimosas, Bloody Marys, and pomegranate sangria. - M.V."
  },
  {
    "id": 025,
    "name": "Cafe Malta",
    "address": "3421 W. William Cannon",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78701",
    "phone number": "(512) 853-9584",
    "brunch": "Weekend, 11am-4pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.cafemaltaaustin.com",
    "review": "This neighborhood gem offers Mediterranean bistro fare in a tasteful, uplifting setting. Brunch goes long here, so it is a great place to go if you are getting a late start on the day. Full espresso bar and cocktail service are definite pluses, but the real draw is the food. Reliably well-executed dishes including croque madame, brisket ravioli, chicken tagine pot pie, steak and eggs, pain perdu, and French onion tart have earned Cafe Malta a following, and the prices are surprisingly low, ranging from $6-11. - K.T."
  },
  {
    "id": 026,
    "name": "Manuel's",
    "address": "10201 Jollyville Rd.",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78759",
    "phone number": "(512) 345-1042",
    "brunch": "Sunday, 10am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.manuels.com",
    "review": "While it's billed as a "jazz brunch," the mood of Interior Mexico is perhaps more appropriately evoked with a traveling group of rootsy mariachis serenading your party as you enjoy tapas-style servings of filled potato tortas, quesadillas, and breakfast tacos. Hungry vegetarians will want to try the Flautas de Papa ($11), potato enchiladas that manage to be both light and filling; carnivores will love the Lomo de Res ($16), an upscale version of steak and eggs. Drink specials include $5 Mexican mimosas (orange juice, sparkling wine, and a splash of Bauchant orange liqueur) and serrano chile-spiked Bloody Marias. Those confined to the Downtown area will find another Manuel's within walking distance, on Congress Avenue. - M.H."
  },
  {
    "id": 027,
    "name": "Bonhomie",
    "address": "5350 Burnet Road",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78756",
    "phone number": "(512) 243-8558",
    "brunch": "Weekend, 11:30am",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "bonhomieaustin.com",
    "review": "While official brunch is on hold for now, dishes from the lunch menu will do for the midmorning meal, like the lox-topped pommes rosti and the soft scrabled egg toast with truffles."
  },
  {
    "id": 028,
    "name": "El Mesón Taquería",
    "address": "2038 S. Lamar",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78704",
    "phone number": "(512) 442-4441",
    "brunch": "Sunday, 10am-2pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.elmesonaustin.wordpress.com",
    "review": "At this affordable brunch buffet in South Austin you will find something for everyone. Start with fresh fruit with granola and yogurt, eggs cooked to order, some chilaquiles verdes and refried beans, or try a cup or two of pozole with traditional trimmings. Then move to the fantastic ceviche, cochinita pibil, fresh paella, and spinach salad with pomegranate seeds, among many other authentic Interior Mexican dishes. Be adventurous and try the smoky Bloody Mary, made with mezcal and a spicy house-made mix, and save room for a visit to the dessert table, which includes a perfect flan, tres leches cake, classic natilla, and other delights. - C.A."
  },
  {
    "id": 029,
    "name": "Josephine House",
    "address": "1601 Waterston",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78703",
    "phone number": "(512) 477-5584",
    "brunch": "Weekend, 11am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.josephineofaustin.com",
    "review": "Following the house's charming makeover in 2013, waitstaff in crisp white waistcoats now serve lunches, drinks, and weekend brunches in the sweet little white dining room and sheltered outdoor nooks. Brunch includes impressive arrays of house-made pastries, cocktails, and menu items like gussied-up biscuits and gravy with a farm egg and sausage ($16), steak hash with sweet potato ($18), various vegetable and grain concoctions, and roasted chicken with panzanella ($15). - MM.P."
  },
  {
    "id": 030,
    "name": "Old Thousand",
    "address": "1000 E 11th St Ste 150",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78702",
    "phone number": "(737) 222-6637",
    "brunch": "Sunday, 11am-2pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.oldthousandatx.com",
    "review": "Seek out dim sum brunch from east side newcomer Old Thousand, with dishes like hot chicken potstickers, dumplings, bao buns, and more."
  },
  {
    "id": 031,
    "name": "Luke’s Inside Out",
    "address": "1109 S Lamar Blvd",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78704",
    "phone number": "(512) 589-8883",
    "brunch": "Sunday, 11:30am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.lukesinsideout.com",
    "review": "Luke's brunch is focused on a la carte dishes with its signature style, take cheesy migas with tater tot hash, chicken fried beef tenderloin, and Sichuan chicken with waffles and brie. Plus, there’s access to Gibson Bar’s dollar mimosas and $5 Bloody Mary bar."
  },
  {
    "id": 032,
    "name": "Grizzelda’s",
    "address": "105 Tillery St",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78702",
    "phone number": "(512) 105 Tillery St",
    "brunch": "Sunday, 10am-2pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "grizzeldas.com",
    "review": "Jacoby’s Mexican restaurant Grizzelda’s offers a Sunday brunch buffet with cooked-to-order egg dishes, enchiladas, taco bar, chilaquiles, and pastries., along with midmorning cocktails like aguas frescas, Bloody Marys, mimosas, and micheladas. It costs $28 per person, $15 for children between the ages of five to 12, and free for anyone under 5 years old."
  },
  {
    "id": 033,
    "name": "Eberly",
    "address": "615 S Lamar Blvd",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78704",
    "phone number": "(512) 916-9000",
    "brunch": "Weekend, 10am-2pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.eberlyaustin.com",
    "review": "The South Lamar restaurant is finally introducing daytime hours with brunch this weekend. The daylight dishes include crab with grits, waffle-fried chickens, hot cakes, and Bloody Marys, orange daiquiri, and mimosas. Brunch cocktails are available after 2 p.m. at the bar within the dining room. "
  },
  {
    "id": 034,
    "name": "El Burro",
    "address": "1100 S Lamar Blvd Suite 1125",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78704",
    "phone number": "(512) 975-2600",
    "brunch": "Daily, 11am-2pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.elburroatx.com",
    "review": "The South Lamar newcomer whips up daily Mexican brunch, with dishes like chilaquiles, breakfast gorditas, and huevos rancheros."
  },
  {
    "id": 035,
    "name": "Soursop",
    "address": "440 E Saint Elmo Rd Ste G-2",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78745",
    "phone number": "not available",
    "brunch": "Sunday, 12pm-10pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.soursopaustin.com",
    "review": "The Thai trailer outside of St. Elmo Brewing Co. dishes out brunch, which means omelet rice, fried chicken and roti, and a pork belly breakfast sandwich."
  },
  {
    "id": 036,
    "name": "Coast Bar and Kitchen",
    "address": "360 Nueces St #20",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78701",
    "phone number": "(512) 850-4673",
    "brunch": "Sunday, 11am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.coastaustin.com",
    "review": "Sunday seafood brunch is back at Coast. Find decadent lobster toast, fried fish sandwiches, omelettes, DIY peel and eat shrimp, and more. For drinks, there are Bloody Marys, mimosas, and cold brew."
  },
  {
    "id": 037,
    "name": "My Name Is Joe Coffee Co.",
    "address": "501 Colorado St",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78701",
    "phone number": "not available",
    "brunch": "Weekdays, 7am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.mynameisjoe.com",
    "review": "To switch things up, seek out weekday brunch courtesy of My Name Is Joe Coffee Co. from Philip Speer. This means granola, oatmeal, toasts topped with almond butter or smoked salmon, and a solid coffee lineup."
  },
  {
    "id": 038,
    "name": "EastSide Tavern",
    "address": "1510 E Cesar Chavez St",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78702",
    "phone number": "(512) 840-1799",
    "brunch": "Weekend, 11am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.eastsidetavernaustin.com/#home",
    "review": "The barbecue take on brunch means Texas toast covered in chopped brisket gravy, brisket hash, turkey avocado toast, and breakfast tacos. You can also add an egg to any of the regular dishes for a morning twist."
  },
  {
    "id": 039,
    "name": "Second Bar + Kitchen",
    "address": "3121 Palm Way",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78758",
    "phone number": "(512) 836-5700",
    "brunch": "Weekend, 11am-2pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.secondbarkitchen.com/second",
    "review": "Second Bar + Kitchen answered the brunch call with its new location up in the Archer Hotel. Take your pick from dishes like crispy French toast, chicken and waffles, and more."
  },
  {
    "id": 040,
    "name": "Isla",
    "address": "208 W 4th St",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78701",
    "phone number": "(737) 222-6906",
    "brunch": "Sunday, 11am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.islaaustin.com",
    "review": "Brunch at Isla took on a Peruvian spin with new dishes like cebiche, coal-cooked tuna, tamal, Peruvian-Chinese fried rice, and more."
  },
  {
    "id": 041,
    "name": "Revelry Kitchen + Bar",
    "address": "1410 E 6th St",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78702",
    "phone number": "(512) 322-5223",
    "brunch": "Sunday, 11am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.revelryatx.com",
    "review": "The East 6th bar's brunch is loaded with honey maple bourbon chicken lollipops and waffles, curry, and ribeye hash skillet. This all pairs with the Bloody Mary bar, mimosas, lavender pisco sour, and more."
  },
  {
    "id": 042,
    "name": "Vinaigrette",
    "address": "2201 College Ave",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78704",
    "phone number": "(512) 852-8791",
    "brunch": "Weekend, 11am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.vinaigretteonline.com/austin_brunch_menu",
    "review": "New Mexico came to Austin with the South Congress salad restaurant. The brunch is full of green and red chiles (and yes, you can get everything Christmas-style) with breakfast sandwiches, steak and eggs, huevos rancheros, and more."
  },
  {
    "id": 043,
    "name": "Foreign & Domestic",
    "address": "306 E 53rd St",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78751",
    "phone number": "(512) 375-4869",
    "brunch": "Sunday, 10:30am-2:30pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.fndaustin.com",
    "review": "Sunday brunch returned to the North Loop restaurant, full of brunch-perfect dishes like fried chicken and sweet potato waffles, cottage cheese pancakes, and pastrami pork belly. Wash everything down with cherry lime mimosas and coffee."
  },
  {
    "id": 044,
    "name": "Patika",
    "address": "2159 S Lamar Blvd",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78704",
    "phone number": "(512) 535-3955",
    "brunch": "Daily, 7am-2pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.patikacoffee.com/southlamar",
    "review": "Patika offers brunch (and breakfast) from its former trailer outside the cafe, delving out the usual staples: toasts (including a take on peanut butter and jelly with stewed sour cherries, almonds, and ricotta), bowls, and sandwiches."
  },
  {
    "id": 045,
    "name": "The Factory",
    "address": "7718 Burnet Rd",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78703",
    "phone number": "(512) 888-9766",
    "brunch": "Weekday, 10am-12am, Weekend, 9am-12am",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.facebook.com/thefactorycafe",
    "review": "The Factory is very obsessed with waffles (so much so that its staffers are called 'waffle architects' and 'waffle prep masters'). Expect chicken and waffles, alongside inventive coffee drinks."
  },
  {
    "id": 046,
    "name": "Epicerie",
    "address": "2307 Hancock Dr",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78756",
    "phone number": "(512) 371-6840",
    "brunch": "Sunday, 10:30am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "epicerieaustin.com",
    "review": "French and New Orleans-inspired brunch from Epicerie equals croque madames, powdered sugar-dusted beignets, and even the Northeastern staple scrapple."
  },
  {
    "id": 047,
    "name": "Bouldin Creek Café",
    "address": "1900 S 1st St",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78704",
    "phone number": "(512) 416-1601",
    "brunch": "Weekend, 8am",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.bouldincreek.com",
    "review": "Vegetarians and vegans have a home with Bouldin Creek Cafe’s brunch. Take advantage of the egg substitute tofu scramble with dishes like tacos, omelets, and breakfast sandwiches."
  },
  {
    "id": 048,
    "name": "Magnolia Cafe South",
    "address": "1920 S Congress Ave",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78704",
    "phone number": "(512) 445-0000",
    "brunch": "Daily, anytime",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "themagnoliacafe.com",
    "review": "The indispensable 24-hour restaurant (with a second location out on Lake Austin Boulevard) is Austin’s brunch hero, doling out pancakes, omelettes, migas, and lunchtime dishes all day and night lunch."
  },
  {
    "id": 049,
    "name": "Launderette",
    "address": "2115 Holly St",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78702",
    "phone number": "(512) 382-1599",
    "brunch": "Weekend, 11am-2:30pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "launderetteaustin.com/",
    "review": "For a classic Bloody Mary, you can’t do better in this town than Launderette. The beautifully balanced drink is the platonic ideal of Bloodies, rich and tomatoey with just the right amount of salt and sour. You won’t find flashy garnishes, just house-made pickles and a smudge of salt."
  },
  {
    "id": 050,
    "name": "Weather Up",
    "address": "1808 East Cesar Chavez",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78702",
    "phone number": "(512) 524-0464",
    "brunch": "Weekend, 11am-3pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.weatherupnyc.com/austin-1",
    "review": ""
  },
  {
    "id": 051,
    "name": "Austin Java",
    "address": "1608 Barton Spring Rd",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78704",
    "phone number": "(512) 482-9450",
    "brunch": "Daily, all day",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.austinjava.com",
    "review": ""
  },
  {
    "id": 052,
    "name": "Mighty Cone",
    "address": "1720 Barton Springs Road",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78704",
    "phone number": "(512) 383-9609",
    "brunch": "Daily, 11am-8pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.mightycone.com",
    "review": ""
  },
  {
    "id": 053,
    "name": "Alta's Cafe",
    "address": "74 Trinity Street",
    "city": "Austin",
    "state": "Texas",
    "zipcode": "78701",
    "phone number": "(512) 499-0470",
    "brunch": "Daily, 8am-8pm",
    "price": "",
    "rating": "",
    "photos": "",
    "website": "www.altascafe.com",
    "review": ""
  }
}
